name: Run Acceptance Tests

on:
  push:
  workflow_dispatch:

jobs:
  run-acc-tests:
    runs-on: ubuntu-latest

    name: Go linux amd64 build
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: .go-version
          cache: true

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: "0"
          VAULT_ACC: 1
          VAULT_ADDR: http://localhost:8200
          VAULT_DEV_LISTEN_ADDRESS: 127.0.0.1:8200
          VAULT_TOKEN: root
        run: make dev

      - name: Run acceptance tests
        run: |
          docker pull vault &&
          docker run -d --name vault --mount type=bind,src=${PWD}/bin,dst=/vault/file --cap-add=IPC_LOCK -p 8200:8200 -e VAULT_ADDR="$VAULT_ADDR" -e VAULT_TOKEN="$VAULT_TOKEN" -e VAULT_DEV_ROOT_TOKEN_ID="$VAULT_TOKEN" -e VAULT_DEV_LISTEN_ADDRESS="$VAULT_DEV_LISTEN_ADDRESS" vault server -dev -dev-plugin-dir /vault/file &&
          timeout 30 sh -c 'until ! docker ps -a; do sleep 1; done'
          vault status
          docker logs vault
          timeout 20 sh -c 'until docker ps -a; do sleep 1; done'
          timeout 30 sh -c 'until docker exec -t vault vault status; do sleep 1; done' &&
          make testacc
